In [2]:
import pandas as pd
from sklearn.cluster import KMeans
import matplotlib as plt

data = pd.read_csv("ObesityDataSet.csv")

In [ ]:
data = pd.read_csv("ObesityDataSet.csv")
data

In [6]:
# Launch always on start only once, else there is the error(if it gives you error it already made changes, ignore that)

data = data.replace({"yes": 1, "no": 0, "Sometimes": 0.25, "Frequently": 0.75, "Always": 1, "Male": 1, "Female": 0})
mtrans = ["Automobile", "Public_Transportation", "Motorbike", "Bike", "Walking"]
for i in mtrans:
    data[i] = 0
    data.loc[data["MTRANS"] == i, i] = 1
data.drop(columns=["MTRANS", "NObeyesdad"], inplace=True)
data

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,Automobile,Public_Transportation,Motorbike,Bike,Walking
0,0,21.000000,1.620000,64.000000,1,0,2.0,3.0,0.25,0,2.000000,0,0.000000,1.000000,0.00,0,1,0,0,0
1,0,21.000000,1.520000,56.000000,1,0,3.0,3.0,0.25,1,3.000000,1,3.000000,0.000000,0.25,0,1,0,0,0
2,1,23.000000,1.800000,77.000000,1,0,2.0,3.0,0.25,0,2.000000,0,2.000000,1.000000,0.75,0,1,0,0,0
3,1,27.000000,1.800000,87.000000,0,0,3.0,3.0,0.25,0,2.000000,0,2.000000,0.000000,0.75,0,0,0,0,1
4,1,22.000000,1.780000,89.800000,0,0,2.0,1.0,0.25,0,2.000000,0,0.000000,0.000000,0.25,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,0,20.976842,1.710730,131.408528,1,1,3.0,3.0,0.25,0,1.728139,0,1.676269,0.906247,0.25,0,1,0,0,0
2107,0,21.982942,1.748584,133.742943,1,1,3.0,3.0,0.25,0,2.005130,0,1.341390,0.599270,0.25,0,1,0,0,0
2108,0,22.524036,1.752206,133.689352,1,1,3.0,3.0,0.25,0,2.054193,0,1.414209,0.646288,0.25,0,1,0,0,0
2109,0,24.361936,1.739450,133.346641,1,1,3.0,3.0,0.25,0,2.852339,0,1.139107,0.586035,0.25,0,1,0,0,0
2110,0,23.664709,1.738836,133.472641,1,1,3.0,3.0,0.25,0,2.863513,0,1.026452,0.714137,0.25,0,1,0,0,0